// <auto-generated />
namespace MVVMStudentsList.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IndeksToInt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IndeksToInt));
        
        string IMigrationMetadata.Id
        {
            get { return "201611201741106_IndeksToInt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
